---
#-------------------------------
# Site Settings
title: WAIX
logo: #"/images/public/logo.png" # You can add own logo. For example '/images/logo.png'.
description: Menca personal blogging theme for Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

#-------------------------------
# Author Settings
author:
  author__name: Bryce
  author__bio: 不是每件事都注定会成功<br>但每件事都值得一试
  author__avatar: "/images/public/01-1.jpg"

social:
  - { icon: "ion-logo-twitter", link: "https://twitter.com/brycewai" }
  - { icon: "ion-logo-github", link: "https://github.com/brycewai" }
  - { icon: "ion-logo-youtube", link: "https://youtube.com" }

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Hero Settings
hero:
  hero__title: Bryce
  hero__description: Victory loves preparation
  hero__image: "/images/public/01.png"

#-------------------------------
# Newsletter
mailchimp: disable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Subscribe here
mailchimp__button__text: Get a new tip

#-------------------------------
# Gallery Footer Section
gallery:
  gallery__title: 本期画廊（不定期更新）
  gallery__columns: 3
  gallery__images:
    - alt: "Lady-in-White-on-the-Beach-at-Trouville"
      url: "/images/gallery/Lady-in-White-on-the-Beach-at-Trouville.jpg"
    - alt: "Boats-at-Zaandam"
      url: "/images/gallery/Boats-at-Zaandam.jpg"
    - alt: "Ritratto-della-marchesa-Casati-con-piume-di-pavone"
      url: "/images/gallery/Ritratto-della-marchesa-Casati-con-piume-di-pavone.jpg"
    - alt: "Hercules-and-Alcestis"
      url: "/images/gallery/Hercules-and-Alcestis.jpg"
    - alt: "Scene-from-the-Romance-of-Amadis-de-Gaule"
      url: "/images/gallery/Scene-from-the-Romance-of-Amadis-de-Gaule.jpg"
    - alt: "The-Death-of-Sardanapalus"
      url: "/images/gallery/The-Death-of-Sardanapalus.jpg"
    # - alt: "Fashion"
    #   url: "/images/106.jpg"
    # - alt: "Notes"
    #   url: "/images/107.jpg"
    # - alt: "Rest"
    #   url: "/images/108.jpg"

#-------------------------------
# Contact Settings
contact:
  email: huaqiang.wei@gmail.com # Add your email for contant form
  description: 您可以直接在下面留言，所有的信息都将保密 # Add a description of your form

# NOTE
# Menso theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: demo-menca # Add your shortname for Disqus Comment. For example demo-menca

#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
